### ISSUE TITLE
Accept converted ASCII files

### ISSUE THREAD

**Issue by kwilcox** [SECOORA/GUTILS#2]
from https://github.com/kerfoot/slocum

**Comment by kerfoot** [comment]
@kwilcox I cleaned up the code in https://github.com/kerfoot/slocum, added documentation and created a new repo:

https://github.com/kerfoot/slocum-utils

Please clone the repo (tag=v1.0-stable), check the wiki doco and test on a few files and let me know if everything works as expected.

**Comment by kwilcox** [comment]
So I will need to copy new flight/science files into a "not processed" folder, run the convert script, and then remove the files from the directory so they don't get parsed again on the next run, correct?. Is that a typical workflow?

**Comment by kerfoot** [comment]
Yes, that's typical.  The issue that you may run into, however, during real-time ops is that the flight data file may be transferred, but the science data file may not (if iridium comms break down before both files are transferred).  In that case, the script would convert only the flight file and create an ascii file missing science data.

I could add an additional command line option (-s or 'strict mode') that would only convert/merge segments with both a flight and science file an delete them if they are successfully merged.  In this case, you would want to copy the original flight and science data files to a queue location and convert/merge the copies.  I'll probably add this option anyways, but let me know if you want/need it and I'll do it first thing tomorrow.

**Comment by kwilcox** [comment]
The ability pipe the output of `convertDbds.sh` somewhere would be real nice and cover lots of use-cases. The output could be the file paths of all files that it used in a conversion to ASCII (something that wouldn't need to be used again).  For example: piping the output to `xargs/rm`, `xargs/mv`, etc.

The `strict` flag would also be nice but I haven't run into that situation before. I always re-create the files at the end of a deployment to fix little issues like this so its not important at the moment.

**Comment by kerfoot** [comment]
1. So you mean print the absolute paths of all files that were successfully converted and merged to STDOUT?
2. You may not have run into this situation before, but you will.  Iridium comms are notoriously bad and we've had many many cases of this happening.  Just warning you now.

The script currently prints conversion/merging progress to STDOUT, but there is a -q option that prevents this.  I'll add a -x option to print the list of all successfully converted/merged files, but you'll still need to specify -q or you'll have to parse this information out.  Will this work?

**Comment by kwilcox** [comment]
That will work: `-q -x`.

**Comment by kerfoot** [comment]
Added -p option to print the paths of successfully converted & merged binary files to STDOUT.  Tag is v1.1.
